name: Send Slack Msg

on:
  issues:
    types: [ opened ]
  pull_request:
    types: [ opened ]

jobs:
  send_slack_msg:
    name: send slack message
    runs-on: ubuntu-latest
    steps:
      - name: set params
        id: params
        run: |
          echo "::set-output name=event_name::${{ github.event_name }}"
          echo "::set-output name=repo_name::${{ github.event.repository.name }}"
          echo "::set-output name=slack_webhook_url::${{ secrets.SLACK_WEBHOOK_URL_SEND_MSG }}"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              echo "::set-output name=event_html_url::${{ github.event.pull_request.html_url }}"
          fi
          if [[ "${{ github.event_name }}" == "issues" ]]; then
              echo "::set-output name=event_html_url::${{ github.event.issue.html_url }}"
          fi
      - name: send ${{ github.event_name }} to slack
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "event_name": "${{ steps.params.outputs.event_name }}",
              "event_html_url": "${{ steps.params.outputs.event_html_url }}",
              "repo_name": "${{ steps.params.outputs.repo_name }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ steps.params.outputs.slack_webhook_url }}
